### ISSUE TITLE
Cannot connect to database

### ISSUE THREAD

**Issue by HomeSchoolDev** [cheprasov/php-redis-client#64]
Hello, I'm running into some issues getting php-redis-client working in my laravel project. I included it in my composer packages and installed it, however, the client cannot connect to the redis. 

"stream_socket_client(): unable to connect to tcp://127.0.0.1:6379 (Connection refused)"

<img width="1953" alt="screen shot 2018-06-21 at 1 04 14 pm" src="https://user-images.githubusercontent.com/792292/41737443-eea5d596-7554-11e8-9326-bade1e16a617.png">

As you can see the redis server is running and I can connect to it using the exact same host and port the codebase is attempting to use: 

<img width="990" alt="screen shot 2018-06-21 at 1 04 25 pm" src="https://user-images.githubusercontent.com/792292/41737478-0a9a57c2-7555-11e8-8e56-a9727d7b24ab.png">
<img width="556" alt="screen shot 2018-06-21 at 1 04 44 pm" src="https://user-images.githubusercontent.com/792292/41737485-0f1fcd18-7555-11e8-8c63-00cee18110a9.png">

Here's my code for reference. 

<img width="494" alt="screen shot 2018-06-21 at 1 06 02 pm" src="https://user-images.githubusercontent.com/792292/41737503-1a0dbe24-7555-11e8-8edf-4c912fcb9976.png">

**Comment by cheprasov** [comment]
Hey @HomeSchoolDev 
I checked and the client works well.
Really it does not look like a problem with the client. It looks like the client tries to connect to a server without a redis-server. 

Please check network setting, firewall (opened ports) and redis config ("protected mode" setting in redis config).
