### ISSUE TITLE
An error occurred while saving a sufficiently long string

### ISSUE THREAD

**Issue by darksoftware** [cheprasov/php-redis-client#67]
**Hello!**

Redis server: 3.2.100 ( OpenServer, Windows )

PHP 7.1 x64

String length === 14000 ( Serialized multilevel array )

Timeout = 60 (!!!)

Method = $Redis->set()

**Result:**
`Uncaught RedisClient\Exception\EmptyResponseException: Empty response. Please, check connection timeout.`

**Why??? What am I doing wrong?**

**Comment by cheprasov** [comment]
Hey @darksoftware 
Please provide more information about the error:

1. RedisClient configuration.
2. Example of code which throws the error.
3. Try to execute the same command in `redis-cli`
4. Try to execute simple command like `$Redis->set('foo', 'bar');`, does it work fine?
5. Check `timeout` and `connection.timeout` in config, check php ini value for `ini_get("default_socket_timeout")`.
6. Check firewall settings.
7. Please show trace of the error.

Please provide maximum description of the error.

**Comment by cheprasov** [comment]
It looks like the question in not actual anymore.
