### ISSUE TITLE
Calling time() from pipeline or multi results in an error

### ISSUE THREAD

**Issue by RichardLowe** [cheprasov/php-redis-client#72]
Hello!  Thanks for this client, works great.

One thing, it seems because there's a `$parserId` set when the `->time()` command is called in multi cases (not sure about pipeline too maybe?), that the client tries to parse the `QUEUED` string result right away resulting in errors like this:

```
FRAME    3. RedisClient\\Client\\AbstractRedisClient->executePipeline(RedisClient\\Pipeline\\Version\\Pipeline5x0 object) /home/vagrant/ttus/debesys/risk/vendor/cheprasov/php-redis-client/src/RedisClient/Client/AbstractRedisClient.php:281
FRAME    4. RedisClient\\Pipeline\\AbstractPipeline->parseResponse(Array) /home/vagrant/ttus/debesys/risk/vendor/cheprasov/php-redis-client/src/RedisClient/Client/AbstractRedisClient.php:235
FRAME    5. RedisClient\\Command\\Response\\ResponseParser::parse(3, "QUEUED") /home/vagrant/ttus/debesys/risk/vendor/cheprasov/php-redis-client/src/RedisClient/Pipeline/AbstractPipeline.php:110
 FRAME    6. RedisClient\\Command\\Response\\ResponseParser::parseTime("QUEUED") /home/vagrant/ttus/debesys/risk/vendor/cheprasov/php-redis-client/src/RedisClient/Command/Response/ResponseParser.php:34
FRAME    7. myErrorHandler(4096, "Argument 1 passed to RedisClient\\Command\\Response\\ResponseParser::parseTime() must be of the type array, string given, called in....
```

Thanks again for the great client!

**Comment by RichardLowe** [comment]
Sorry, in the subject I said pipeline - again not sure maybe just a multi pipeline not pipeline alone - not sure.

**Comment by cheprasov** [comment]
Hi @RichardLowe 
Thanks a lot for the issue, I will fix it soon :)

**Comment by cheprasov** [comment]
Hi @RichardLowe 
I created branch `v191` https://github.com/cheprasov/php-redis-client/tree/v191
Now, the bug should be fixed.
Could you please check your code with the branch if it is possible? 
I am going to realise a new version soon.
Thanks.
