### ISSUE TITLE
Variadic functions when array in arg

### ISSUE THREAD

**Issue by MarcTCruz** [cheprasov/php-redis-client#77]
This project seems pretty well developed and I guess it'll rock on PHP 8 where people will more and more write and seek for extensions written directly in php.

Here is my suggestion:
Functions like hmget can easily become variadic to comply with Redis docs and without breaking changes for users like that:
```
    public function hmget($key, ...$fields) {
        if(is_array($fields[0]))
            $fields = $fields[0];
        return $this->returnCommand(['HMGET'], $key, [$key, (array) $fields]);
    }
```

This way, it can be called:
```
    $redis->hmget("key", "field1", "field2");
        or
    $redis->hmget("key", ["field1", "field2"]);

```

**Comment by cheprasov** [comment]
hi @MarcTCruz 

Thanks a lot. Looks good. Current redis client support wide ranges of php versions (5.5 - 7.4). I am planning to stop support old php version and realise new redis client version only for php 7.4 +.

Thanks a lot :)
